package ro.octa.greendaosample.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dBUserDaoConfig;
    private final DaoConfig dBUserDetailsDaoConfig;
    private final DaoConfig dBPhoneNumberDaoConfig;

    private final DBUserDao dBUserDao;
    private final DBUserDetailsDao dBUserDetailsDao;
    private final DBPhoneNumberDao dBPhoneNumberDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dBUserDaoConfig = daoConfigMap.get(DBUserDao.class).clone();
        dBUserDaoConfig.initIdentityScope(type);

        dBUserDetailsDaoConfig = daoConfigMap.get(DBUserDetailsDao.class).clone();
        dBUserDetailsDaoConfig.initIdentityScope(type);

        dBPhoneNumberDaoConfig = daoConfigMap.get(DBPhoneNumberDao.class).clone();
        dBPhoneNumberDaoConfig.initIdentityScope(type);

        dBUserDao = new DBUserDao(dBUserDaoConfig, this);
        dBUserDetailsDao = new DBUserDetailsDao(dBUserDetailsDaoConfig, this);
        dBPhoneNumberDao = new DBPhoneNumberDao(dBPhoneNumberDaoConfig, this);

        registerDao(DBUser.class, dBUserDao);
        registerDao(DBUserDetails.class, dBUserDetailsDao);
        registerDao(DBPhoneNumber.class, dBPhoneNumberDao);
    }
    
    public void clear() {
        dBUserDaoConfig.getIdentityScope().clear();
        dBUserDetailsDaoConfig.getIdentityScope().clear();
        dBPhoneNumberDaoConfig.getIdentityScope().clear();
    }

    public DBUserDao getDBUserDao() {
        return dBUserDao;
    }

    public DBUserDetailsDao getDBUserDetailsDao() {
        return dBUserDetailsDao;
    }

    public DBPhoneNumberDao getDBPhoneNumberDao() {
        return dBPhoneNumberDao;
    }

}
