package ro.octa.greendaosample.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import android.os.Parcel;
import android.os.Parcelable;

/**
 * Entity mapped to table DBPHONE_NUMBER.
 */
public class DBPhoneNumber implements Parcelable {

    private Long id;
    /**
     * Not-null value.
     */
    private String phoneNumber;
    private long detailsId;

    public DBPhoneNumber() {
    }

    public DBPhoneNumber(Long id) {
        this.id = id;
    }

    public DBPhoneNumber(Long id, String phoneNumber, long detailsId) {
        this.id = id;
        this.phoneNumber = phoneNumber;
        this.detailsId = detailsId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Not-null value.
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    public long getDetailsId() {
        return detailsId;
    }

    public void setDetailsId(long detailsId) {
        this.detailsId = detailsId;
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeValue(this.id);
        dest.writeString(this.phoneNumber);
        dest.writeLong(this.detailsId);
    }

    private DBPhoneNumber(Parcel in) {
        this.id = (Long) in.readValue(Long.class.getClassLoader());
        this.phoneNumber = in.readString();
        this.detailsId = in.readLong();
    }

    public static final Creator<DBPhoneNumber> CREATOR = new Creator<DBPhoneNumber>() {
        public DBPhoneNumber createFromParcel(Parcel source) {
            return new DBPhoneNumber(source);
        }

        public DBPhoneNumber[] newArray(int size) {
            return new DBPhoneNumber[size];
        }
    };
}
