package ro.octa.greendaosample.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "DBPHONE_NUMBER".
 */
public class DBPhoneNumber {

    private Long id;
    /**
     * Not-null value.
     */
    private String phoneNumber;
    private long detailsId;

    public DBPhoneNumber() {
    }

    public DBPhoneNumber(Long id) {
        this.id = id;
    }

    public DBPhoneNumber(Long id, String phoneNumber, long detailsId) {
        this.id = id;
        this.phoneNumber = phoneNumber;
        this.detailsId = detailsId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    public long getDetailsId() {
        return detailsId;
    }

    public void setDetailsId(long detailsId) {
        this.detailsId = detailsId;
    }

}
